### ISSUE TITLE
google翻译问题

### ISSUE THREAD

**Issue by shipengtaov** [littlecodersh/translation#2]
google翻译返回结果 json 解析后可能是 list，也可能是字符串。

如果是字符串，返回的结果就有问题了，会只返回第一个字符，比如这个：

<img width="660" alt="2016-07-10 10 58 44" src="https://cloud.githubusercontent.com/assets/4241969/16714342/3df17580-46f2-11e6-8a59-eb66196853b8.png">

**Comment by littlecodersh** [comment]
@shispt 多谢，已在新版本中修复
